### ISSUE TITLE
Update chronograf version to at least 1.7.8

### ISSUE THREAD

**Issue by gcox** [influxdata/digitalocean-marketplace#2]
Anyone setting this stack up is quickly welcomed to the TICK stack with an error caused by a bug that was fixed 3 months ago: https://github.com/influxdata/chronograf/pull/5078

**Comment by gunnaraasen** [comment]
We're working on an updated image with the latest versions.

**Comment by gunnaraasen** [comment]
The DO marketplace image has been updated to Chronograf v1.7.12.

We've switched to Packer for building the image so it will be easier for us to regularly publish updated images compared to the manual process.
